CIRCUITPY_WIFI_SSID = "CIA Bug"
CIRCUITPY_WIFI_PASSWORD = "Project2"
ADAFRUIT_AIO_USERNAME = "NBrouwer"
ADAFRUIT_AIO_KEY = "aio_XGkx29GBaVu3QEKwSmepTzKWPZdB"
USE_WIFI = "true"
WIFI_UPDATE_SPEED = "1"